version: '3.3'
services:
 bot:
  container_name: bot
  build:
   context: .
   dockerfile: bot/dockerfile
  env_file: .env
  ports:
   - "8082:8001" 
  depends_on:
   - db_api
  restart: always
 api:
  container_name: api
  build:
   context: .
   dockerfile: backend/docker/dockerfile
  command:  gunicorn bot_weather.wsgi:application --bind 0.0.0.0:8000
  ports:
   - "8083:8000"
  depends_on:
   - db_api
  restart: always
  env_file:
   - .env
 db_api:
  container_name: db_api
  image: postgres:15.6
  volumes:
   - postgres_data:/var/lib/postgresql/data/
  ports:
   - 5433:5432
  env_file:
   - .env
  restart: always


 nginx:
  restart: unless-stopped
  image: nginx:latest
  depends_on:
   - api
  ports:
   - "8084:80"
  volumes:
   - ./backend/docker/nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
 postgres_data:
