FROM python:3.12-slim-bullseye
                                                                            
ENV APP_HOME=/home/app/bot
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

COPY ./bot/requirements.txt .
RUN pip install -r requirements.txt

COPY ./bot $APP_HOME

CMD ["python3", "main_weather_bot.py"]